// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_6ffUd79GUJq4OSrImFaKN2DPzoirlJc',
    appId: '1:1091524110711:ios:794bd7d332c84101705972',
    messagingSenderId: '1091524110711',
    projectId: 'prayer-box-flutter',
    storageBucket: 'prayer-box-flutter.firebasestorage.app',
    iosBundleId: 'com.example.prayerBoxFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_6ffUd79GUJq4OSrImFaKN2DPzoirlJc',
    appId: '1:1091524110711:ios:794bd7d332c84101705972',
    messagingSenderId: '1091524110711',
    projectId: 'prayer-box-flutter',
    storageBucket: 'prayer-box-flutter.firebasestorage.app',
    iosBundleId: 'com.example.prayerBoxFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJIsanl-mZKnKLnvNonTvJKNanlXl7tg',
    appId: '1:1091524110711:web:ab754e2e6ddd805b705972',
    messagingSenderId: '1091524110711',
    projectId: 'prayer-box-flutter',
    authDomain: 'prayer-box-flutter.firebaseapp.com',
    storageBucket: 'prayer-box-flutter.firebasestorage.app',
    measurementId: 'G-ZZRZY2ZF0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbikPwJob3Ker8jn1oiX2bQGjzl_ITqWI',
    appId: '1:1091524110711:android:d803654f238c7e62705972',
    messagingSenderId: '1091524110711',
    projectId: 'prayer-box-flutter',
    storageBucket: 'prayer-box-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJIsanl-mZKnKLnvNonTvJKNanlXl7tg',
    appId: '1:1091524110711:web:fd8e903959b1addf705972',
    messagingSenderId: '1091524110711',
    projectId: 'prayer-box-flutter',
    authDomain: 'prayer-box-flutter.firebaseapp.com',
    storageBucket: 'prayer-box-flutter.firebasestorage.app',
    measurementId: 'G-3GGYRM091W',
  );

}